### ISSUE TITLE
Won't Work on Python Versions > 3.6 Due to Enum

### ISSUE THREAD

**Issue by finalised** [10se1ucgo/cue_sdk#9]
I had issues getting the package to work on Python 3.6, so I downgraded to Python 3.2 and it still didn't work. I then read somewhere that between versions 3.4 and 3.5 they changed the way the enum module worked. 

**To fix this, I installed Python 3.5.0 and it's all good now.** 

Just want to put this here in case others are looking for a solution.

**Comment by 10se1ucgo** [comment]
Yeah, I have a fix locally but I haven't pushed it. I'll push it in a day or two.

**Comment by bradMatias** [comment]
can you please push the new version?

**Comment by 10se1ucgo** [comment]
Yeah sorry I started work into other things. For now, open the `enumerations.py` file and replace each instance of `(with_metaclass(KeywordMeta, CEnum))` to just `(CEnum, metaclass=KeywordMeta)`

e.g.

```py
class CLK(with_metaclass(KeywordMeta, CEnum)):
```

becomes

```py
class CLK(CEnum, metaclass=KeywordMeta):
```

Note this breaks Python 2.x compatibility. I'll get around to finding a backwards compatible fix sometime

**Comment by bradMatias** [comment]
That didn't work for 3.5 or 3.6, and I really would like it to work with 2.7, but I get this error when I try to run it.  Any idea why?

`    from cue_sdk import *
  File "C:\Python27\lib\site-packages\cue_sdk\__init__.py", line 1, in <module>
    from .api import *
  File "C:\Python27\lib\site-packages\cue_sdk\api.py", line 7, in <module>
    from .enumerations import *
  File "C:\Python27\lib\site-packages\cue_sdk\enumerations.py", line 1, in <module>
    from enum import EnumMeta, Enum
ImportError: cannot import name EnumMeta`

**Comment by 10se1ucgo** [comment]
Should be fixed by #10. Very sorry for the long wait,  been busy with other things.
